### ISSUE TITLE
How do you build this?

### ISSUE THREAD

**Issue by srid** [aforemny/elm2nix#1]
My current attempts to get this building on NixOS are failing:

```
$ stack init --nix
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- elm2nix.cabal

Selecting the best among 11 snapshots...

* Partially matches lts-9.0
    aeson version 1.1.2.0 found
        - elm2nix requires ==0.6.*

Downloaded nightly-2017-08-13 build plan.
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```

**Comment by aforemny** [comment]
Hi,
this project is outdated: it probably does not comply with current state of Elm anymore. I wrote this four years ago when Elm did not have package management. How come you are trying to run this - what's your need?

**Comment by srid** [comment]
Understood. 

I found a different version of elm2nix too. However Elm as it stands right now seems not to be a good fit for Nix based development. Ref: https://github.com/NixOS/nixpkgs/issues/20601#issuecomment-289056588

**Comment by domenkozar** [comment]
See https://github.com/domenkozar/elm2nix
